version: '3'
services:
  postgres:
    container_name: nestjs-drizzle-postgres
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env

networks:
  postgres:
    driver: bridge
