version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: reverser-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend
    restart: always
    networks:
      - monitoring

  frontend:
    image: psm-ui:react-ts
    container_name: psm-ui
    build:
      context: ./react-ts
      dockerfile: Dockerfile
    volumes:
      - ./nginx.fe.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
    networks:
      - monitoring

  backend:
    image: psm-api:nestjs-drizzle
    container_name: psm-api
    build:
      context: ./nestjs-drizzle
      dockerfile: Dockerfile
    env_file:
      - ./nestjs-drizzle/.env
    restart: always
    networks:
      - monitoring

networks:
  monitoring:
    external: true
