version: "3"

services:
  frontend:
    image: psm-ui:react-ts
    container_name: psm-ui
    build:
      context: ./react-ts
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 3000:80
    depends_on:
      - backend
    restart: always

  backend:
    image: psm-api:nestjs-drizzle
    container_name: psm-api
    build:
      context: ./nestjs-drizzle
      dockerfile: Dockerfile
    env_file:
      - ./nestjs-drizzle/.env
    restart: always
