apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    editable: true

  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    jsonData:
      tokenUri: https://oauth2.googleapis.com/token
      clientEmail: psm-monitoring@latian-415403.iam.gserviceaccount.com
      authenticationType: jwt
      defaultProject: latian-415403
      privateKeyPath: /etc/secrets/psm-monitoring-sa.key

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    editable: true
